name: "rss-issues"
author: "Guilhem Lettron"
description: "Create Issues based on RSS"
branding:
  icon: "rss"
  color: "orange"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
  feed:
    description: "URL of the rss"
  prefix:
    description: "Prefix added to issues"
  lastTime:
    description: "limit RSS items to this time"
  labels:
    description: "Labels to add, comma separated"
  dry-run:
    description: "Log issue creation but do nothing"
  aggregate:
    description: "Aggregate all items in a single issue"
  characterLimit:
    description: "Limit size of issue content"
  titleFilter:
    description: "Filter out entries whose titles match this regex"
  contentFilter:
    description: "Filter out entries whose contents match this regex"
outputs:
  issues:
    description: "issues id, comma separated"
runs:
  using: "docker"
  image: "Dockerfile"
